### ISSUE TITLE
Pre-trained model for the uncertainty version

### ISSUE THREAD

**Issue by Crowbar97** [Halmstad-University/SalsaNext#14]
Great job, @TiagoCortinhal!
Could you please share the pre-trained model for the new uncertainty version of SalsaNext?
Thank you in advance!

**Comment by TiagoCortinhal** [comment]
Hello @Crowbar97! The uncertainty version is simply a wrap-up of the network after training following [A General Framework for Uncertainty Estimation in Deep Learning](https://arxiv.org/abs/1907.06890).

**Comment by TiagoCortinhal** [comment]
Hey @Crowbar97, I forgot to mention that the pretrained is on the readme (here it is the direct link https://cutt.ly/bpadjGj)
