### ISSUE TITLE
About Number of Parameters and FLOPs

### ISSUE THREAD

**Issue by iris0329** [Halmstad-University/SalsaNext#17]
Thank you for opening the source code of this briliant work!

The values of **Number of Parameters** and **FLOPs** are shown in the paper.

I'm curious how do you calculate these two values? 
Which tools/packages do you use for calculation?

Best, 
Iris

**Comment by TiagoCortinhal** [comment]
Hello @iris0329!

For the **Number of Parameters** we used the built-in functions of Pytorch like so: `sum(p.numel() for p in  model.parameters() if p.requires_grad)`

For the **FLOPs** we used this package: https://github.com/sovrasov/flops-counter.pytorch


Best,
Tiago

**Comment by iris0329** [comment]
@TiagoCortinhal Thank you for your generous reply！
