### ISSUE TITLE
How to run this on windows 10.

### ISSUE THREAD

**Issue by Shivas219** [Halmstad-University/SalsaNext#20]
I am very new to this field. I have 3d lidar point cloud data and videos. My task is to do semantic segmentation of that data for further investigation.
Can anyone help me that how can I do that. Can I use any pre-traind model. And how.

**Comment by TiagoCortinhal** [comment]
@Shivas219 Hello!

I cannot give you a definitive answer as I do not use Windows, but anaconda is also available for windows. You can try to start by creating the environment for SalsaNext and check if some dependencies are missing and try to find alternatives for windows.

For the pre-trained model, yes you can use it. They are not OS-dependent.
