### ISSUE TITLE
arch_cfg.yaml not found

### ISSUE THREAD

**Issue by SoftwareApe** [Halmstad-University/SalsaNext#24]
infer.py tries to load arch_cfg.yaml and data_cfg.yaml. Neither file can be found.

```python
    # open arch config file
    try:
        print("Opening arch config file from %s" % FLAGS.model)
        ARCH = yaml.safe_load(open(FLAGS.model + "/arch_cfg.yaml", 'r'))
    except Exception as e:
        print(e)
        print("Error opening arch yaml file.")
        quit()

    # open data config file
    try:
        print("Opening data config file from %s" % FLAGS.model)
        DATA = yaml.safe_load(open(FLAGS.model + "/data_cfg.yaml", 'r'))
    except Exception as e:
        print(e)
        print("Error opening data yaml file.")
        quit()
```

**Comment by sebaleme** [comment]
We can retrain the model to generate them, but then providing the model alone is not enough

**Comment by TiagoCortinhal** [comment]
@sebaleme I will upload them later today but you can use the ones generated by retraining (with standard options) as it will be the same.

**Comment by sebaleme** [comment]
Hi, The arch_conf is in the repo, but not at the expected position: it is directly at the root level, with the following name: salsanext.yml

**Comment by TiagoCortinhal** [comment]
@sebaleme, kNN should work in both types of projections, but for the scope of this paper we focused on SFV.
