### ISSUE TITLE
Problem with visualization of qualitative results

### ISSUE THREAD

**Issue by leezhp1994** [Halmstad-University/SalsaNext#31]
I have a question. How to use prediction tags to visualize point clouds for qualitative display, or which visualization tools are used? (That is, convert the predicted label at the bottom to the 3d point cloud view at the top)
E.g:
![image](https://user-images.githubusercontent.com/49901905/97276456-2883d980-1872-11eb-868b-1a65b7668ec3.png)

**Comment by TiagoCortinhal** [comment]
Hello @leezhp1994!

Sorry for the late answer, you can find all the visualisation related code here:
[visualization.py](https://github.com/Halmstad-University/SalsaNext/blob/master/train/common/visualization.py)
[laserscanvis.py](https://github.com/Halmstad-University/SalsaNext/blob/master/train/common/laserscanvis.py)
