### ISSUE TITLE
img_means in salsanext.yml

### ISSUE THREAD

**Issue by fcyeh** [Halmstad-University/SalsaNext#4]
Thanks for the great work.
I wonder why X-coordinate is around 10? I get around 0. (sequence 00-10 except 08)
mean in salsanext.yml: (12.12, **10.88**, 0.23,  -1.04, 0.21)
Here is my mean: (11.562, **-0.107**, 0.502, -1.060, 0.287)
Can you provide how you calculate the mean?

**Comment by TiagoCortinhal** [comment]
Hey!

Sorry for the delay in answering!

We didn't recompute the mean values for the dataset (we used the values provided by the authors of RangeNet++), but you raise a good question. I will put that on my todo list and re-compute them just to make sure. 

Best
