### ISSUE TITLE
Some inference questions about final mean and variance

### ISSUE THREAD

**Issue by fcyeh** [Halmstad-University/SalsaNext#41]
![image](https://user-images.githubusercontent.com/26170029/101427406-a4cafd00-38b3-11eb-9b4f-0a04a6751fa5.png)
Based on the paper "A General Framework for Uncertainty Estimation in Deep Learning", I have questions about your inference code in user.py.

1. Should the final prediction be average of proj_output_r or proj_output2? The equation from the paper is average of T times monte-carlo predictions.
https://github.com/Halmstad-University/SalsaNext/blob/cc8c75dc68d2607d16e2c82be61e7254e5b74a12/train/tasks/semantic/modules/user.py#L157

2. Is log_var2 sensor uncertainty? If yes, based on the equation, we just need to do average. Why did you do log_var_r.var()?
https://github.com/Halmstad-University/SalsaNext/blob/cc8c75dc68d2607d16e2c82be61e7254e5b74a12/train/tasks/semantic/modules/user.py#L159

Thank you.

**Comment by TiagoCortinhal** [comment]
Hello @fcyeh!

It should be yes, but given our output is not a linear like in their case, taking directly the mean did not work.

**Comment by fcyeh** [comment]
Hi @TiagoCortinhal. Thank you for the response. I think you were talking about question 1 right?
How about question 2, the sensor uncertainty? Why need to do var before average?
https://github.com/Halmstad-University/SalsaNext/blob/cc8c75dc68d2607d16e2c82be61e7254e5b74a12/train/tasks/semantic/modules/user.py#L159
![image](https://user-images.githubusercontent.com/26170029/101666278-dbfbf400-3a02-11eb-8653-52b7f759e58d.png)
Thank you.

**Comment by TiagoCortinhal** [comment]
Yes it should be mean. This was corrected!

**Comment by fcyeh** [comment]
Thank you!
