### ISSUE TITLE
Pretrained model : dead link

### ISSUE THREAD

**Issue by loukabvn** [Halmstad-University/SalsaNext#58]
Hello,
I'm a French student and I make an internship onto semantic segmentation, so I need to run your code, but the link to the pretrained model seems dead. If you have the time, can you update your link or send me another ?
Thank you !
(Sorry if it's not the place to ask that I'm not very familiar with Github)

**Comment by TiagoCortinhal** [comment]
Salut!

I had an issue with my google drive. I will try to fix it as soon as possible!

**Comment by loukabvn** [comment]
Thank you very much !

**Comment by univjun** [comment]
Hi. TiagoCortinhal
Your results are impressive. 
I want to run your code. 
Could you fix the link to the pretrained model?

Thank you

**Comment by TiagoCortinhal** [comment]
Thank you for reminding me!

I updated the link!
