### ISSUE TITLE
Question about redundancy of code in user.py

### ISSUE THREAD

**Issue by samhithaaaa** [Halmstad-University/SalsaNext#70]
Hi,

I see that in user.py script, lines 228 to 234 are same as lines 236 to 242.
if torch.cuda.is_available():
                torch.cuda.synchronize()
            res = time.time() - end
            print("Network seq", path_seq, "scan", path_name,
                  "in", res, "sec")
            end = time.time()
            cnn.append(res)

Why is the code repeating twice, or is it by mistake that this piece of code is written twice, or is there any interpretation to it?

Someone please help!

**Comment by TiagoCortinhal** [comment]
It was clearly a case of mistake. You can delete the extra one and do a PR if you'd like
